export default {
  ime_prezime_default: "",
  userActiveState: false,
  userMail: null,
  searchTags: "",
  marke: [
    { marka: "Abarth", modeli: ["500", "Grande Punto"] },
    {
      marka: "Alfa Romeo",
      modeli: [
        "33",
        "146",
        "147",
        "156",
        "156 SW",
        "159",
        "159 SW",
        "Brera",
        "Giulia",
        "Giulietta",
        "GT",
        "MiTo",
        "Spider",
        "Sprint",
        "Stelvio",
        "Tonale",
      ],
    },
    {
      marka: "Aston Martin",
      modeli: [
        "DB",
        "DBS",
        "DBX",
        "DB7",
        "DB9",
        "Lagonda",
        "Vanquish",
        "Vantage",
        "Virage",
        "Volante",
      ],
    },
    {
      marka: "Audi",
      modeli: [
        "80",
        "100",
        "A1",
        "A2",
        "A3",
        "A4",
        "A3 Coupe",
        "A3 Cabrio",
        "A4 Cabrio",
        "A4 Allroad",
        "A4 Avant",
        "A5 Coupe",
        "A5 Sportback",
        "A5 Cabrio",
        "A6 Avant",
        "A6 Allroad",
        "A6",
        "A7",
        "A8",
        "e-tron",
        "Q2",
        "Q3",
        "Q4 e-tron",
        "Q5",
        "Q7",
        "Q8",
        "R8",
        "RS3",
        "RS4",
        "RS5",
        "RS6",
        "RS7",
        "S1",
        "S3",
        "S4 Avant",
        "S5",
        "S6",
        "S6 Avant",
        "S8",
        "TT",
        "RSQ8",
        "SQ7",
        "TTRS",
      ],
    },
    {
      marka: "Bentley",
      modeli: [
        "Arnage",
        "Azure",
        "Bentayga",
        "Brooklands",
        "Continental",
        "Continental Flying Spur",
        "Continental GT",
        "Continental GTC",
        "Continental Supersports",
        "Mulsanne",
      ],
    },
    {
      marka: "BMW",
      modeli: [
        "1 Series",
        "2 Series",
        "3 Series",
        "4 Series",
        "5 Series",
        "6 Series",
        "7 Series",
        "8 Series",
        "X1",
        "X2",
        "X3",
        "X3 M",
        "X4",
        "X4 M",
        "X5",
        "X5 M",
        "X6",
        "X6 M",
        "X7",
        "X8",
        "Z3",
        "Z4",
        "Z8",
      ],
    },
    {
      marka: "Cadillac",
      modeli: [
        "ATS",
        "ATS-V",
        "BLS",
        "CT4",
        "CT5",
        "CT6",
        "CTS",
        "CTS-V",
        "DeVille",
        "DTS",
        "Eldorado",
        "ELR",
        "Escalade",
        "Seville",
        "SRX",
        "STS",
        "STS-V",
        "XLR",
        "XT4",
        "XT5",
        "XT6",
        "XTS",
        "XTS Platinum",
      ],
    },
    {
      marka: "Chevrolet",
      modeli: [
        "Alero",
        "Astro",
        "Avalanche",
        "Aveo",
        "Blazer",
        "Camaro",
        "Caprice",
        "Captiva",
        "Cavalier",
        "Celebrity",
        "Citation",
        "Colorado",
        "Corsica",
        "Corvette",
        "Cruze",
        "Epica",
        "Equinox",
        "Evanda",
        "Express",
        "HHR",
        "Impala",
        "Kalos",
        "Lacetti",
        "Lanos",
        "Lumina",
        "Malibu",
        "Monte Carlo",
        "Niva",
        "Nubira",
        "Orlando",
        "Rezzo",
        "S-10",
        "Silverado",
        "Sonora",
        "Spark",
        "Suburban",
        "Tahoe",
        "Tavera",
        "TrailBlazer",
        "Traverse",
        "Trax",
        "Uplander",
        "Venture",
        "Volt",
      ],
    },
    {
      marka: "Chrysler",
      modeli: [
        "300M",
        "300C",
        "Aspen",
        "Cirrus",
        "Concorde",
        "Crossfire",
        "Daytona",
        "Grand Voyager",
        "Intrepid",
        "Le Baron",
        "LHS",
        "Neon",
        "New Yorker",
        "Pacifica",
        "Prowler",
        "PT Cruiser",
        "Saratoga",
        "Sebring",
        "Stratus",
        "Town & Country",
        "Viper",
        "Vision",
        "Voyager",
      ],
    },
    {
      marka: "Citroën",
      modeli: [
        "2CV",
        "Acadiane",
        "AMI",
        "AX",
        "Axel",
        "Berlingo",
        "BX",
        "C-Crosser",
        "C-Elysée",
        "C-ZERO",
        "C1",
        "C2",
        "C3",
        "C3 Aircross",
        "C3 Picasso",
        "C3 Pluriel",
        "C4",
        "C4 Aircross",
        "C4 Cactus",
        "C4 Picasso",
        "C5",
        "C5 Aircross",
        "C6",
        "C8",
        "C15",
        "C25",
        "CX",
        "DS",
        "DS3",
        "DS4",
        "DS5",
        "Evasion",
        "Grand C4 Picasso",
        "GS",
        "GSA",
        "Jumper",
        "Jumpy",
        "LNA",
        "Nemo",
        "Saxo",
        "SM",
        "SpaceTourer",
        "Traction Avant",
        "Visa",
        "Xantia",
        "XM",
        "Xsara",
        "Xsara Picasso",
        "ZX",
      ],
    },
    {
      marka: "Cupra",
      modeli: ["Ateca", "Formentor", "Leon", "Tavascan"],
    },
    {
      marka: "Dacia",
      modeli: [
        "Dokker",
        "Duster",
        "Logan",
        "Logan MCV",
        "Lodgy",
        "Nova",
        "Sandero",
        "Sandero Stepway",
        "Spring",
      ],
    },
    {
      marka: "Daewoo",
      modeli: [
        "Espero",
        "Evanda",
        "Kalos",
        "Korando",
        "Lacetti",
        "Lanos",
        "Leganza",
        "Lublin",
        "Magnus",
        "Matiz",
        "Musso",
        "Nexia",
        "Nubira",
        "Rezzo",
        "Tacuma",
      ],
    },
    {
      marka: "Daihatsu",
      modeli: [
        "Applause",
        "Charade",
        "Copen",
        "Cuore",
        "Feroza",
        "Gran Move",
        "Hijet",
        "Materia",
        "Move",
        "Rocky",
        "Sirion",
        "Terios",
        "Trevis",
        "YRV",
      ],
    },
    {
      marka: "Dodge",
      modeli: [
        "Avenger",
        "Caliber",
        "Caravan",
        "Challenger",
        "Charger",
        "Dakota",
        "Dart",
        "Durango",
        "Grand Caravan",
        "Intrepid",
        "Journey",
        "Magnum",
        "Neon",
        "Nitro",
        "Ram",
        "Ram Van",
        "Shadow",
        "Spirit",
        "Stealth",
        "Stratus",
        "Viper",
      ],
    },
    {
      marka: "DFSK",
      modeli: [
        "Glory",
        "Pick Up",
        "Serena",
        "V Series",
        "X5",
        "iX5",
        "EC35",
        "EC36W",
        "EC37W",
        "EC50",
        "EC70",
        "EC80",
        "EC90",
        "EC95",
      ],
    },
    {
      marka: "DS Automobiles",
      modeli: ["DS 3", "DS 4", "DS 5", "DS 7 Crossback", "DS 9"],
    },
    {
      marka: "Ferrari",
      modeli: [
        "208",
        "308",
        "328",
        "348",
        "360",
        "365",
        "400",
        "412",
        "430",
        "456",
        "458",
        "488",
        "512",
        "550",
        "575",
        "599",
        "612",
        "812 Superfast",
        "California",
        "F8 Tributo",
        "FF",
        "Fiorano",
        "FXX",
        "GTC4Lusso",
        "Mondial",
        "Portofino",
        "Roma",
        "SF90 Stradale",
      ],
    },
    {
      marka: "Fiat",
      modeli: [
        "124 Spider",
        "124",
        "126",
        "127",
        "128",
        "130",
        "131",
        "132",
        "500",
        "500L",
        "500X",
        "600",
        "850",
        "Albea",
        "Argenta",
        "Barchetta",
        "Brava",
        "Bravo",
        "Cinquecento",
        "Coupé",
        "Croma",
        "Doblo",
        "Ducato",
        "Fiorino",
        "Freemont",
        "Fullback",
        "Grande Punto",
        "Idea",
        "Linea",
        "Marea",
        "Multipla",
        "Palio",
        "Panda",
        "Punto",
        "Qubo",
        "Regata",
        "Ritmo",
        "Scudo",
        "Sedici",
        "Seicento",
        "Siena",
        "Stilo",
        "Strada",
        "Talento",
        "Tempra",
        "Tipo",
        "Ulysse",
        "Uno",
        "X1/9",
      ],
    },
    {
      marka: "Ford",
      modeli: [
        "Aerostar",
        "Aspire",
        "B-Max",
        "Bronco",
        "C-Max",
        "Capri",
        "Contour",
        "Cougar",
        "Courier",
        "Crown Victoria",
        "Econoline",
        "Ecosport",
        "Edge",
        "Escape",
        "Escort",
        "Excursion",
        "Expedition",
        "Explorer",
        "F 150",
        "F 250",
        "F 350",
        "F 450",
        "F 550",
        "Fairlane",
        "Fairmont",
        "Falcon",
        "Fiesta",
        "Five Hundred",
        "Flex",
        "Focus",
        "Fusion",
        "Galaxy",
        "Granada",
        "KA",
        "Kuga",
        "Maverick",
        "Mondeo",
        "Mustang",
        "Orion",
        "Probe",
        "Puma",
        "Ranger",
        "S-Max",
        "Scorpio",
        "Sierra",
        "Taurus",
        "Thunderbird",
        "Tourneo",
        "Transit",
        "Transit Connect",
        "Transit Courier",
        "Transit Custom",
        "Windstar",
      ],
    },
    {
      marka: "Forthing",
      modeli: ["500"],
    },
    {
      marka: "Geely",
      modeli: [
        "Atlas",
        "Beauty Leopard",
        "CK",
        "Emgrand",
        "Emgrand 7",
        "Emgrand X7",
        "FC",
        "GC2",
        "GC7",
        "GC9",
        "GL",
        "GL Proton",
        "Ig",
        "KC",
        "LC",
        "LC Cross",
        "MK",
        "MK Cross",
        "MK Proton",
        "MKing",
        "MR",
        "NL",
        "Otaka",
        "Panda",
        "TX4",
        "Vision",
        "X7",
      ],
    },
    {
      marka: "GMC",
      modeli: [
        "Acadia",
        "Caballero",
        "Canyon",
        "Envoy",
        "Jimmy",
        "Safari",
        "Savana",
        "Sierra",
        "Sonoma",
        "Suburban",
        "Syclone",
        "Terrain",
        "Tracker",
        "Typhoon",
        "Vandura",
        "Yukon",
      ],
    },
    {
      marka: "Great Wall Motor",
      modeli: [
        "Deer",
        "Hover",
        "Peri",
        "Piker",
        "Safe",
        "Sing",
        "Socool",
        "Wingle",
      ],
    },
    {
      marka: "Honda",
      modeli: [
        "Accord",
        "Beat",
        "Civic",
        "Concerto",
        "CR-V",
        "CRX",
        "CR-Z",
        "Element",
        "Elysion",
        "FR-V",
        "HR-V",
        "Insight",
        "Integra",
        "Jazz",
        "Legend",
        "NSX",
        "Odyssey",
        "Pilot",
        "Prelude",
        "Quintet",
        "S2000",
        "Shuttle",
        "Stream",
      ],
    },
    {
      marka: "Hummer",
      modeli: ["H1", "H2", "H3"],
    },
    {
      marka: "Hyundai",
      modeli: [
        "Accent",
        "Atos",
        "Bongo",
        "Coupé",
        "Elantra",
        "Entourage",
        "Excel",
        "Genesis",
        "Getz",
        "Grand Santa Fe",
        "Grandeur",
        "H-1",
        "i10",
        "i20",
        "i30",
        "i40",
        "IONIQ",
        "ix20",
        "ix35",
        "ix55",
        "Kona",
        "Lantra",
        "Matrix",
        "Nexo",
        "Palisade",
        "Pony",
        "Santa Fe",
        "Santro",
        "Sonata",
        "Starex",
        "Terracan",
        "Tiburon",
        "Trajet",
        "Tucson",
        "Veloster",
        "Venue",
        "XG",
      ],
    },
    {
      marka: "Infiniti",
      modeli: [
        "EX",
        "FX",
        "G",
        "I30",
        "J30",
        "JX",
        "M",
        "Q30",
        "Q40",
        "Q45",
        "Q50",
        "Q60",
        "Q70",
        "QX",
        "QX30",
        "QX50",
        "QX60",
        "QX70",
        "QX80",
      ],
    },
    {
      marka: "Isuzu",
      modeli: [
        "Amigo",
        "Aska",
        "Axiom",
        "Campo",
        "D-Max",
        "Faster",
        "Gemini",
        "KB",
        "MU",
        "Piazza",
        "Rodeo",
        "TF",
        "Trooper",
        "VehiCross",
      ],
    },
    {
      marka: "Iveco",
      modeli: ["Daily", "Massif", "TurboDaily"],
    },
    {
      marka: "Jaguar",
      modeli: [
        "E-Type",
        "F-PACE",
        "F-Type",
        "I-PACE",
        "S-Type",
        "X-Type",
        "XE",
        "XF",
        "XJ",
        "XK",
        "XKR",
        "XKR-S",
        "XKR-S GT",
      ],
    },
    {
      marka: "Jeep",
      modeli: [
        "Cherokee",
        "Commander",
        "Compass",
        "Grand Cherokee",
        "Patriot",
        "Renegade",
        "Wrangler",
      ],
    },
    {
      marka: "Kia",
      modeli: [
        "Carens",
        "Carnival",
        "Ceed",
        "Ceed SW",
        "Cerato",
        "Clarus",
        "Forte",
        "Joice",
        "Magentis",
        "Niro",
        "Opirus",
        "Optima",
        "Optima SW",
        "Picanto",
        "Pregio",
        "Pro Ceed",
        "Rio",
        "Seltos",
        "Sephia",
        "Shuma",
        "Sorento",
        "Soul",
        "Sportage",
        "Stinger",
        "Stonic",
        "Venga",
        "Xceed",
      ],
    },
    {
      marka: "Lada",
      modeli: [
        "110",
        "111",
        "112",
        "4x4",
        "Granta",
        "Kalina",
        "Largus",
        "Niva",
        "Priora",
        "Samara",
        "Taiga",
        "Vesta",
        "XRAY",
      ],
    },
    {
      marka: "Lamborghini",
      modeli: [
        "Aventador",
        "Countach",
        "Diablo",
        "Espada",
        "Gallardo",
        "Huracan",
        "Jalpa",
        "LM002",
        "Miura",
        "Murcielago",
        "Reventon",
        "Urus",
        "Veneno",
      ],
    },
    {
      marka: "Lancia",
      modeli: [
        "Beta",
        "Dedra",
        "Delta",
        "Flaminia",
        "Flavia",
        "Fulvia",
        "Gamma",
        "Kappa",
        "Lybra",
        "Monte Carlo",
        "Mus",
        "Phedra",
        "Prisma",
        "Stratos",
        "Thema",
        "Thesis",
        "Voyager",
        "Y",
        "Ypsilon",
      ],
    },
    {
      marka: "Land Rover",
      modeli: [
        "Defender",
        "Discovery",
        "Discovery Sport",
        "Freelander",
        "Range Rover",
        "Range Rover Evoque",
        "Range Rover Sport",
        "Range Rover Velar",
      ],
    },
    {
      marka: "Lexus",
      modeli: [
        "CT",
        "ES",
        "GS",
        "IS",
        "LC",
        "LS",
        "LX",
        "NX",
        "RC",
        "RX",
        "SC",
        "UX",
      ],
    },
    {
      marka: "Lincoln",
      modeli: [
        "Aviator",
        "Continental",
        "Corsair",
        "LS",
        "Mark",
        "MKC",
        "MKS",
        "MKT",
        "MKX",
        "MKZ",
        "Navigator",
        "Town Car",
        "Zephyr",
      ],
    },
    {
      marka: "Lotus",
      modeli: ["Elan", "Elise", "Elite", "Esprit", "Europa", "Evora", "Exige"],
    },
    {
      marka: "Lynk & Co",
      modeli: ["01"],
    },
    {
      marka: "Maserati",
      modeli: [
        "228",
        "3200 GT",
        "420",
        "4200 GT",
        "430",
        "Biturbo",
        "Ghibli",
        "GranCabrio",
        "GranSport",
        "GranTurismo",
        "Indy",
        "Karif",
        "Kyalami",
        "Levante",
        "MC12",
        "Merak",
        "Mexico",
        "Quattroporte",
        "Shamal",
        "Spyder",
      ],
    },
    {
      marka: "Mazda",
      modeli: [
        "121",
        "2",
        "3",
        "323",
        "323 F",
        "323 P",
        "323 S",
        "5",
        "6",
        "616",
        "626",
        "818",
        "929",
        "Atenza",
        "AZ-1",
        "B2500",
        "Bongo",
        "BT-50",
        "Capella",
        "Carol",
        "CX-3",
        "CX-30",
        "CX-5",
        "CX-7",
        "CX-9",
        "Demio",
        "E2200",
        "Eunos",
        "Eunos 500",
        "Eunos Cosmo",
        "Familia",
        "Lantis",
        "Millenia",
        "MPV",
        "MX-3",
        "MX-30",
        "MX-5",
        "MX-6",
        "Premacy",
        "Proceed",
        "Proceed Levante",
        "Protege",
        "RX-7",
        "RX-8",
        "Sentia",
        "Spiano",
        "Tribute",
        "Verisa",
        "Xedos",
      ],
    },
    {
      marka: "McLaren",
      modeli: [
        "540C",
        "570GT",
        "570S",
        "600LT",
        "620R",
        "650S",
        "675LT",
        "720S",
        "Artura",
        "Elva",
        "F1",
        "GT",
        "P1",
        "Sabre",
        "Senna",
      ],
    },
    {
      marka: "Mercedes-Benz",
      modeli: [
        "A-Class",
        "AMG GT",
        "B-Class",
        "C-Class",
        "CL-Class",
        "CLA-Class",
        "CLC-Class",
        "CLK-Class",
        "CLS-Class",
        "E-Class",
        "G-Class",
        "GL-Class",
        "GLA-Class",
        "GLB-Class",
        "GLC-Class",
        "GLC Coupe",
        "GLE-Class",
        "GLE Coupe",
        "GLK-Class",
        "GLS-Class",
        "M-Class",
        "R-Class",
        "S-Class",
        "SL-Class",
        "SLC-Class",
        "SLK-Class",
        "SLR McLaren",
        "SLS AMG",
        "V-Class",
        "X-Class",
      ],
    },
    {
      marka: "MG",
      modeli: [
        "F",
        "MG 3",
        "MG 5",
        "MG 6",
        "MG 7",
        "MG ZS",
        "TF",
        "ZR",
        "ZS",
        "ZT",
      ],
    },
    {
      marka: "MINI",
      modeli: [
        "Cabrio",
        "Clubman",
        "Convertible",
        "Coupe",
        "Countryman",
        "Paceman",
        "Roadster",
      ],
    },
    {
      marka: "Mitsubishi",
      modeli: [
        "3000 GT",
        "ASX",
        "Carisma",
        "Celeste",
        "Challenger",
        "Colt",
        "Cordia",
        "Diamante",
        "Eclipse",
        "FTO",
        "Galant",
        "Grandis",
        "i-MiEV",
        "L 200",
        "L 300",
        "Lancer",
        "Lancer Evo",
        "Mirage",
        "Montero",
        "Outlander",
        "Pajero",
        "Pajero Pinin",
        "Pajero Sport",
        "Santamo",
        "Sapporo",
        "Savrin",
        "Shogun",
        "Sigma",
        "Space Gear",
        "Space Runner",
        "Space Star",
        "Space Wagon",
        "Starion",
        "Tredia",
        "Zinger",
      ],
    },
    {
      marka: "MPM",
      modeli: ["PS160", "PS550"],
    },
    {
      marka: "Nissan",
      modeli: [
        "100 NX",
        "200 SX",
        "280 ZX",
        "300 ZX",
        "350Z",
        "370Z",
        "Almera",
        "Almera Tino",
        "Altima",
        "Armada",
        "Bluebird",
        "Cabstar",
        "Cherry",
        "Cube",
        "Evalia",
        "Frontier",
        "GT-R",
        "Interstar",
        "Juke",
        "King Cab",
        "Kubistar",
        "Leaf",
        "Maxima",
        "Micra",
        "Murano",
        "Navara",
        "Note",
        "NP300",
        "NV200",
        "NV400",
        "Oti",
        "Pathfinder",
        "Patrol",
        "Pickup",
        "Pixo",
        "Prairie",
        "Primastar",
        "Primera",
        "Pulsar",
        "Qashqai",
        "Quest",
        "Rogue",
        "Safari",
        "Serena",
        "Silvia",
        "Skyline",
        "Stanza",
        "Sunny",
        "Terrano",
        "Tiida",
        "Tino",
        "Titan",
        "Urvan",
        "Vanette",
        "X-Trail",
        "Z",
        "Z24",
      ],
    },
    {
      marka: "Opel",
      modeli: [
        "Adam",
        "Agila",
        "Ampera",
        "Antara",
        "Ascona",
        "Astra",
        "Calibra",
        "Campo",
        "Cascada",
        "Combo",
        "Commodore",
        "Corsa",
        "Crossland X",
        "Frontera",
        "GT",
        "Insignia",
        "Kadett",
        "Karl",
        "Manta",
        "Meriva",
        "Mokka",
        "Monterey",
        "Monza",
        "Movano",
        "Omega",
        "Rekord",
        "Senator",
        "Signum",
        "Sintra",
        "Speedster",
        "Tigra",
        "Vectra",
        "Vivaro",
        "Zafira",
        "Zafira Life",
        "Zafira-e",
      ],
    },
    {
      marka: "Peugeot",
      modeli: [
        "1007",
        "104",
        "106",
        "107",
        "108",
        "2008",
        "204",
        "205",
        "206",
        "207",
        "208",
        "3008",
        "301",
        "304",
        "305",
        "306",
        "307",
        "308",
        "309",
        "4007",
        "4008",
        "404",
        "405",
        "406",
        "407",
        "5008",
        "504",
        "505",
        "508",
        "604",
        "605",
        "607",
        "806",
        "807",
        "Bipper",
        "Boxer",
        "Expert",
        "iOn",
        "J5",
        "J9",
        "Partner",
        "RCZ",
        "Rifter",
        "Traveller",
      ],
    },
    {
      marka: "Polestar",
      modeli: ["1"],
    },
    {
      marka: "Pontiac",
      modeli: [
        "6000",
        "Aztek",
        "Bonneville",
        "Firebird",
        "Fiero",
        "G3",
        "G5",
        "G6",
        "G8",
        "Grand Am",
        "Grand Prix",
        "GTO",
        "Le Mans",
        "Montana",
        "Solstice",
        "Sunbird",
        "Sunfire",
        "Tempest",
        "Torrent",
        "Trans Sport",
        "Vibe",
      ],
    },
    {
      marka: "Porsche",
      modeli: [
        "356",
        "911",
        "912",
        "914",
        "924",
        "928",
        "959",
        "968",
        "996",
        "Boxster",
        "Carrera GT",
        "Cayenne",
        "Cayman",
        "Macan",
        "Panamera",
        "Taycan",
      ],
    },
    {
      marka: "Puch",
      modeli: ["G", "Haflinger"],
    },
    {
      marka: "Renault",
      modeli: [
        "11",
        "12",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "25",
        "30",
        "4",
        "5",
        "6",
        "9",
        "Alaskan",
        "Arkana",
        "Avantime",
        "Captur",
        "Clio",
        "Clio RS",
        "Duster",
        "Espace",
        "Fluence",
        "Fuego",
        "Grand Espace",
        "Grand Modus",
        "Grand Scénic",
        "Kadjar",
        "Kangoo",
        "Kaptur",
        "Koleos",
        "Kwid",
        "Laguna",
        "Latitude",
        "Lodgy",
        "Logan",
        "Master",
        "Megane",
        "Modus",
        "Rapid",
        "Safrane",
        "Sandero",
        "Scala",
        "Scénic",
        "Sport Spider",
        "Symbol",
        "Talisman",
        "Thalia",
        "Trafic",
        "Twingo",
        "Twizy",
        "Vel Satis",
        "Wind",
        "ZOE",
      ],
    },
    {
      marka: "Rolls-Royce",
      modeli: [
        "Camargue",
        "Corniche",
        "Cullinan",
        "Dawn",
        "Ghost",
        "Park Ward",
        "Phantom",
        "Silver Cloud",
        "Silver Dawn",
        "Silver Seraph",
        "Silver Shadow",
        "Silver Spirit",
        "Silver Spur",
        "Wraith",
      ],
    },
    {
      marka: "Rover",
      modeli: [
        "100",
        "200",
        "25",
        "400",
        "45",
        "600",
        "75",
        "800",
        "Metro",
        "Streetwise",
        "Tourer",
      ],
    },
    {
      marka: "Saab",
      modeli: [
        "600",
        "90",
        "900",
        "9000",
        "9-2X",
        "9-3",
        "9-4X",
        "9-5",
        "9-7X",
        "9-X",
        "Sonett",
        "Sonett III",
      ],
    },
    {
      marka: "Seat",
      modeli: [
        "Alhambra",
        "Altea",
        "Arona",
        "Ateca",
        "Cordoba",
        "Exeo",
        "Ibiza",
        "Leon",
        "Malaga",
        "Marbella",
        "Mii",
        "Ronda",
        "Tarraco",
        "Toledo",
        "Tribu",
      ],
    },
    {
      marka: "Smart",
      modeli: [
        "City-Coupé",
        "City-Coupe",
        "Crossblade",
        "Forfour",
        "Fortwo",
        "Roadster",
      ],
    },
    {
      marka: "Ssang Yong",
      modeli: [
        "Actyon",
        "Chairman",
        "Korando",
        "Kyron",
        "Musso",
        "Rexton",
        "Roda",
        "Stavic",
        "Tivoli",
        "XLV",
      ],
    },
    {
      marka: "Subaru",
      modeli: [
        "Alcyone",
        "Baja",
        "BRZ",
        "Domingo",
        "Forester",
        "Impreza",
        "Justy",
        "Legacy",
        "Leone",
        "Libero",
        "Outback",
        "Pleo",
        "SVX",
        "Tribeca",
        "Vivio",
        "WRX",
        "XT",
        "XV",
      ],
    },
    {
      marka: "Suzuki",
      modeli: [
        "Alto",
        "Baleno",
        "Cappuccino",
        "Celerio",
        "Grand Vitara",
        "Ignis",
        "Jimny",
        "Kizashi",
        "Liana",
        "R",
        "Samurai",
        "Splash",
        "Swift",
        "SX4",
        "Vitara",
        "Wagon R+",
        "X-90",
      ],
    },
    {
      marka: "Škoda",
      modeli: [
        "100",
        "105",
        "120",
        "130",
        "Citigo",
        "Enyaq",
        "Fabia",
        "Favorit",
        "Felicia",
        "Kamiq",
        "Karoq",
        "Kodiaq",
        "Octavia",
        "Popular",
        "Roomster",
        "Rapid",
        "Scala",
        "Superb",
        "Yeti",
      ],
    },
    {
      marka: "Tesla",
      modeli: [
        "Model 3",
        "Model S",
        "Model X",
        "Model Y",
        "Roadster",
        "Semi",
        "Cybertruck",
        "Model 2",
      ],
    },
    {
      marka: "Trabant",
      modeli: [
        "600",
        "601",
        "603",
        "605",
        "Duo",
        "Kombi",
        "Kübel",
        "Limousine",
        "Universal",
      ],
    },
    {
      marka: "Toyota",
      modeli: [
        "4Runner",
        "Alphard",
        "Auris",
        "Avanza",
        "Avensis",
        "Aygo",
        "C-HR",
        "Camry",
        "Carina",
        "Celica",
        "Corolla",
        "Corona",
        "Cressida",
        "Crown",
        "Dyn",
        "FJ Cruiser",
        "Fortuner",
        "GT86",
        "Hiace",
        "Highlander",
        "Hilux",
        "iQ",
        "Land Cruiser",
        "Mirai",
        "MR2",
        "Paseo",
        "Picnic",
        "Previa",
        "Prius",
        "Proace",
        "RAV4",
        "Sequoia",
        "Sienna",
        "Soarer",
        "Starlet",
        "Supra",
        "Tercel",
        "Tundra",
        "Urban Cruiser",
        "Venza",
        "Verso",
        "Yaris",
      ],
    },
    {
      marka: "USA",
      modeli: [
        "Dart",
        "Demon",
        "Eagle",
        "Ghost",
        "GT",
        "Liberty",
        "Muscle",
        "Pacifica",
        "Plymouth",
        "Ram",
        "Rumble Bee",
        "Shelby",
        "Stealth",
        "Sundance",
        "Super Bee",
        "SUV",
        "Thunderbolt",
        "Turbo",
        "USA Muscle",
        "Valiant",
        "Viper",
      ],
    },
    {
      marka: "Volvo",
      modeli: [
        "240",
        "340",
        "360",
        "440",
        "460",
        "480",
        "66",
        "740",
        "760",
        "780",
        "850",
        "940",
        "960",
        "C30",
        "C70",
        "CX",
        "P1800",
        "P240",
        "P260",
        "P445",
        "S40",
        "S60",
        "S70",
        "S80",
        "S90",
        "V40",
        "V40 Cross Country",
        "V50",
        "V60",
        "V60 Cross Country",
        "V70",
        "V90",
        "V90 Cross Country",
        "XC40",
        "XC60",
        "XC70",
        "XC90",
      ],
    },
    {
      marka: "VW",
      modeli: [
        "Amarok",
        "Arteon",
        "Beetle",
        "Bora",
        "Caddy",
        "California",
        "Caravelle",
        "CC",
        "Corrado",
        "Eos",
        "Golf",
        "ID.3",
        "ID.4",
        "Jetta",
        "Lupo",
        "Multivan",
        "Passat",
        "Phaeton",
        "Polo",
        "Scirocco",
        "Sharan",
        "T-Cross",
        "T-Roc",
        "Tiguan",
        "Touareg",
        "Touran",
        "Transporter",
        "Up",
        "Vento",
      ],
    },
    {
      marka: "Wartburg",
      modeli: ["353", "411", "412", "Wartburg 312", "Wartburg 313"],
    },
    {
      marka: "XEV",
      modeli: ["320"],
    },
    {
      marka: "Yugo",
      modeli: [
        "45",
        "55",
        "60",
        "65",
        "70",
        "85",
        "Cabrio",
        "Florida",
        "GV",
        "GVL",
        "GVS",
        "Koral",
        "Koral In",
        "Skala",
        "Zastava 101",
        "Zastava 128",
        "Zastava 750",
      ],
    },
    {
      marka: "Zastava",
      modeli: ["Florida", "Florida In", "Koral", "Koral In", "Skala", "Yugo"],
    },
  ],
};
